:garykl-creation-date: 12/27/2023
:nofooter:
== Who I am

As a Cloud System Architect, I do a lot of talking to people, a bit on business, and a lot on technical stuff. I preserve my technical skills by 'doing' technical things as well.

I've been a passionate software engineer for about six years, working on the backend with dotnet, mainly. My focus has been on domain design and service communication.

As a physicist, I did computer simulations on density functional theory on atomic gold structures and hydrodynamics of biological microswimmers as well as data extraction from videos made from biological experiments.

I've always been a programming language lover, from a practical point of view, so I tried to learn a set of languages as diverse as useful. So Brainfuck is not language of my interest, but many, many others.

== Who I want to be

I'm writing, since I like to reflect on my learnings. As an architect, I'm exposed to a variety of topics, and I'm looking forward to draw connections between topics from my past with current topics.
